Add Deemix
PAPAMICA/docker-compose-collection pull request #5
Opened 2022-09-28 06:40 UTC by QJoly

Je créé cette petite PR car j'avais le compose de Deemix pas très loin. 

C'est également l'occasion de voir si le format passe dans le CI.. :smiley: (J'ai édité à la main le yaml pour que ça match avec ton format portainer)

2022-09-28 06:57 UTC, PAPAMICA requested changes
Quelques petites soucis à fixer 😉

2022-09-28 06:57 UTC, PAPAMICA commented on composes-files/deemix.yml
> +#% SERVICE: Name of the service (No spaces or points) [hastebin]
Modifier `hastebin`en `deemix`

2022-09-28 06:57 UTC, PAPAMICA commented on composes-files/deemix.yml
> +    image: registry.gitlab.com/bockiii/deemix-docker # official developer
Attention à l'espace après `developer`

2022-09-28 06:57 UTC, PAPAMICA commented on composes-files/deemix.yml
> +      - 6595:6595
Pourquoi ouvrir un port si tu le fait passer par Traefik ?

2022-09-28 06:57 UTC, PAPAMICA commented on composes-files/deemix.yml
> +        - "traefik.http.routers.$SERVICE.tls.certresolver=cloudflare"
Le `certresolver` n'est pas standard (`http`).

Bonne idée d'amélioration : le variabiliser.

2022-09-28 06:59 UTC, PAPAMICA commented on composes-files/deemix.yml
> +        - "traefik.http.routers.$SERVICE.tls.certresolver=cloudflare"
Pareil pour l'entrypoint

2022-09-28 07:01 UTC, QJoly commented
Noté :+1:  
Je corrige ça dans la matiné

2022-09-28 07:03 UTC, QJoly commented on composes-files/deemix.yml
> +      - 6595:6595
Parce que le conteneur n'était pas hébergé sur la machine Traefik. J'utilisais le projet traefik-kop (https://github.com/jittering/traefik-kop) pour continuer à avoir des règles dynamiques en passant par mon LAN. 

(Je détaille car c'est la seule erreur "justifié")

2022-10-03 07:35 UTC, QJoly commented
Ping :smiley: 

(Comme ça si le format est OK, j'ouvrirai d'autres PR)

2022-10-03 08:14 UTC, PAPAMICA commented
Impeccable, merci pour ta contribution <3

2022-10-03 08:14 UTC, merged